version: '3'
services:

  node-app:
    build: .
    ports:
      - "3000:3000"
      
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home

volumes:
  jenkins_data: